openapi: 3.0.3
info:
  title: Twitter Process API
  version: '1.0'
  description: |2


    Generated Open API:

    - **openApi.yml**: Documentation of the Processes (this Documentation😊).
    - **postmanOpenApi.yml**: Open Api that you can import to Postman!
      Be aware that this needs some adjustments.

    >WARNING: This is an experimental way and not approved.

    There is no README.md in the Project.

    There is no CHANGELOG.md in the Package.
paths:
  /Process/TwitterDemoP:
    head:
      tags:
      - TwitterDemoP
      summary: TwitterDemoP
      description: This runs the Twitter Approvement Process.
      operationId: 'Process: TwitterDemoP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTweet'
            examples:
              standard:
                value:
                  email: me@myself.com
                  content: Test Tweet
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewTweet'
              examples:
                standard:
                  value:
                    approved: true
  /UserTask/ReviewTweetUT:
    head:
      tags:
      - TwitterDemoP
      summary: ReviewTweetUT
      description: ''
      operationId: 'UserTask: ReviewTweetUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoInput'
            examples:
              standard:
                value: {}
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewTweet'
              examples:
                standard:
                  value:
                    approved: true
                Tweet accepted:
                  value:
                    approved: true
                Tweet rejected:
                  value:
                    approved: false
components:
  schemas:
    CreateTweet:
      required:
      - email
      - content
      type: object
      properties:
        email:
          type: string
        content:
          type: string
      description: |
        Every employee may create a Tweet.

        - email:   The email address of the creator.
        - content: The content of the Tweet.
    NoInput:
      type: object
    ReviewTweet:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Tweet
      description: Every Tweet has to be accepted by the Boss.
