version: "3.7"
services:

  camunda:
    image: camunda/camunda-bpm-platform:latest
    networks:
      - mynet
    #volumes:
    # if you need to customize bpm-platform.xml
    # - ./install/camunda/7.10.0/bpm-platform.xml:/camunda/conf/bpm-platform.xml
    environment:
        TZ: "Europe/Zurich"
        DB_DRIVER: "org.postgresql.Driver"
        DB_URL: "jdbc:postgresql://camunda-db:5432/camunda"
        DB_USERNAME: "postgres"
        DB_PASSWORD: "Initial@Password"
        DB_TEST_ON_BORROW: "true"
        ADMIN_USERNAME: "kermit"
        ADMIN_PASSWORD: "kermit"
        ADMIN_FIRSTNAME: "Kermit"
        ADMIN_LASTNAME: "The Frog"
        ADMIN_EMAIL: "kermit@pme123.com"
        WAIT_FOR: "camunda-db:5432"
    ports:
      - "8085:8080"
    hostname: camunda
    depends_on:
      - camunda-db
      - create-dbs-camunda
