### docker-compose file for demo environment
# Usage:
# docker-compose -f ./examples/docker-compose-dev.yml --project-directory . -p camunda-db up

version: "3.7"
services:

  camunda-db:
    image: postgres
    volumes:
      - camunda-db-vol:/var/lib/postgresql
    networks:
      - mynet
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Initial@Password
      - POSTGRES_DB=postgres
    ports:
      - "5444:5432"
    hostname: camunda-db

  create-dbs-camunda:
    image: boxfuse/flyway
    networks:
      - mynet
    volumes:
      - ./create-dbs-camunda:/flyway/sql
    command: migrate -url=jdbc:postgresql://camunda-db:5432/postgres -user=postgres -password=Initial@Password -schemas=create-dbs -connectRetries=10
    depends_on:
      - camunda-db

volumes:
  camunda-db-vol:

networks:
  mynet:
