server:
  port: 9998

camunda:
  bpm:
    admin-user:
      id: kermit
      password: kermit
      firstName: Kermit
      lastName: The Frog
    filter:
      create: All tasks
    database:
      schema-update: true
      type: postgres
    auto-deployment-enabled: false

spring:
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5433/camunda"
    username: postgres
    password: Initial@Password
    driverClassName: org.postgresql.Driver
    initialization-mode: always

    main.banner-mode: off

logging.level.org.springframework: ERROR
