openapi: 3.0.3
info:
  title: Invoice Example Process API
  version: '1.0'
  summary: "\n**This is for Postman - to have example requests. Be aware the Output\
    \ is not provided!**\n\n\n\nCreated at 13/01/2023, 08:12\n\n**[Check Project on\
    \ Cawemo](https://cawemo.com/folders/a76e4b8e-8631-4d20-a8eb-258b000ff88a--camundala)**\n\
    \n> This is the invoice demo application which is shipped with the full distributions\
    \ in Camunda 7.\n\nSee the original [README](https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice).\n\
    \nI bundled it here! Just run `InvoiceProcessApplication`.\n\n> This requires\
    \ that **Camunda 8 Standalone** is running -> _https://github.com/camunda/camunda-platform.git_\n\
    \nThis based on this Project: https://github.com/pme123/spring-boot-datakurre-plugins\n\
    \n## Migration BPMN/DMN to Camunda 8\n### Pain Points\n- The Migration Plugin\
    \ did not work for DMNs - I had to adjust the XML manually.\n- Forms can not be\
    \ linked (copy-paste Json of form) (Standalone version).\n- Camunda Property Infos\
    \ Plugin does not work.\n- FEEL is missing _**not** myProperty_ - you need to\
    \ do it _myProperty = false_.\n- CallActivities Input-Mapping were not migrated.\n\
    \n### What did not work\n- Forms in the Start Event\n  - Workaround: Added another\
    \ UserTask \n  - but with this, it is impossible to have Camunda Processes running\
    \ by itself (no other application must be deployed)\n- No files\n  - Workaround:\
    \ only the reference to the file is in the process.\n- Dynamic content in Form\
    \ Texts (FEEL)\n- Datastore / Data object reference have no graphic anymore\n\n\
    ### Cool stuff\n- Some code completion in FEEL expressions\n- Links in the Modeller\
    \ to the documentation\n\n## Migrating Camundala to Camunda 8\nThe work to migrate\
    \ the Example concerning:\n- API Documentation\n- Test Simulation\n- Validation\n\
    \n### API Documentation\nNothing to do here - the API stays the same! \U0001f389\
    \U0001f389\U0001f389\n### Test Simulation\n\n\n\n# Changelog\n\n<details>\n<summary>CHANGELOG.md</summary>\n\
    <p>\n\n\nAll notable changes to this project will be documented in this file.\n\
    \n* Types of Changes (L3):\n  * Added: new features\n  * Changed: changes in existing\
    \ functionality\n  * Deprecated: soon-to-be-removed features\n  * Removed: now\
    \ removed features\n  * Fixed: any bug fixes\n  * Security: in case of vulnerabilities\n\
    \n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\n\
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\
    \n### Unreleased\nInitial Version\n\n</p>\n</details>\n\n\n"
servers:
- url: http://localhost:8034/engine-rest
  description: Local Developer Server
paths:
  /decision-definition/key/{key}/--REMOVE:invoice-assign-approver--/evaluate:
    post:
      tags:
      - DMNs
      summary: 'InvoiceAssignApproverDMN: EvaluateDecision'
      description: |2


        Decision Table on who must approve the Invoice.

        <iframe src="https://cawemo.com/embed/155ba236-d5d1-42f7-8b56-3e90e0bb98d4" style="width:100%;height:500px;border:1px solid #ccc" allowfullscreen></iframe>


        Decision DMN:
        - _decisionDefinitionKey_: `invoice-assign-approver`,


        See API Doc: [InvoiceAssignApproverDMN](No URL defined for invoice-example/OpenApi.html#operation/DecisionDmn:%20invoice-assign-approver)
      operationId: postDecision-definitionKeyKey--remove:invoice-assign-approver--Evaluate
      parameters:
      - name: key
        in: path
        description: The Process- or Decision-DefinitionKey of the Process or Decision
        required: true
        schema:
          type: string
          default: invoice-assign-approver
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluateDecisionIn'
            examples:
              InvoiceAssignApproverDMN:
                value:
                  variables:
                    amount:
                      value: 30.0
                      type: Double
                    invoiceCategory:
                      value: Software License Costs
                      type: String
        required: true
      responses:
        '200':
          description: ''
components:
  schemas:
    CBoolean:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: boolean
        type:
          type: string
    CDouble:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: number
          format: double
        type:
          type: string
    CFile:
      required:
      - value
      - valueInfo
      - type
      type: object
      properties:
        value:
          type: string
          description: The File's content as Base64 encoded String.
        valueInfo:
          $ref: '#/components/schemas/CFileValueInfo'
        type:
          type: string
    CFileValueInfo:
      required:
      - filename
      type: object
      properties:
        filename:
          type: string
        mimetype:
          type: string
    CInteger:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: integer
          format: int32
        type:
          type: string
    CJson:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: string
        type:
          type: string
    CLong:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: integer
          format: int64
        type:
          type: string
    CNull:
      type: object
    CString:
      required:
      - value
      - type
      type: object
      properties:
        value:
          type: string
        type:
          type: string
    CamundaVariable:
      oneOf:
      - $ref: '#/components/schemas/CBoolean'
      - $ref: '#/components/schemas/CDouble'
      - $ref: '#/components/schemas/CFile'
      - $ref: '#/components/schemas/CInteger'
      - $ref: '#/components/schemas/CJson'
      - $ref: '#/components/schemas/CLong'
      - $ref: '#/components/schemas/CNull'
      - $ref: '#/components/schemas/CString'
    EvaluateDecisionIn:
      required:
      - variables
      type: object
      properties:
        variables:
          $ref: '#/components/schemas/Map_CamundaVariable'
      description: 'A JSON object with the following properties:'
    Map_CamundaVariable:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CamundaVariable'
