openapi: 3.0.3
info:
  title: Invoice Example Process API
  version: '1.0'
  summary: |2+


    Created at 13/06/2023, 07:42

    ****

    > This is the invoice demo application which is shipped with the full distributions.

    See the original [README](https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice).

    I bundled it here! Just run `InvoiceServletProcessApplication`.

    This based on this Project: https://github.com/pme123/spring-boot-datakurre-plugins


    # Changelog

    <details>
    <summary>CHANGELOG.md</summary>
    <p>


    All notable changes to this project will be documented in this file.

    * Types of Changes (L3):
      * Added: new features
      * Changed: changes in existing functionality
      * Deprecated: soon-to-be-removed features
      * Removed: now removed features
      * Fixed: any bug fixes
      * Security: in case of vulnerabilities


    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

    ### Unreleased
    Initial Version

    </p>
    </details>

paths:
  /process/example-invoice-c7:
    head:
      tags:
      - example-invoice-c7
      summary: 'Process: example-invoice-c7'
      description: |+
        This starts the Invoice Receipt Process.


        <div class="diagramCanvas">
          <div class="diagram" id="example-invoice-c7-38156">
            <img onLoad="openFromUrl('example-invoice-c7.bpmn', new BpmnJS({ container: $('#example-invoice-c7-38156'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [example-invoice-c7.bpmn](diagrams/example-invoice-c7.bpmn)

      operationId: 'Process: example-invoice-c7'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
            examples:
              example-invoice-c7:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out1'
              examples:
                example-invoice-c7:
                  value:
                    approved: true
  /decisiondmn/example-invoice-c7/example-invoice-c7-assignApprover:
    head:
      tags:
      - example-invoice-c7
      summary: 'DecisionDmn: example-invoice-c7-assignApprover'
      description: |+
        Decision Table on who must approve the Invoice.


        <div class="diagramCanvas">
          <div class="diagram" id="example-invoice-c7-assignApprover-29945">
            <img onLoad="openFromUrl('example-invoice-c7-assignApprover.dmn', new DmnJS({ container: $('#example-invoice-c7-assignApprover-29945'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [example-invoice-c7-assignApprover.dmn](diagrams/example-invoice-c7-assignApprover.dmn)

      operationId: 'DecisionDmn: example-invoice-c7-assignApprover'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In1'
            examples:
              example-invoice-c7-assignApprover:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              budget:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              day-to-day expense:
                value:
                  amount: 125.0
                  invoiceCategory: Misc
              exceptional:
                value:
                  amount: 12345.0
                  invoiceCategory: Misc
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]'
              examples:
                example-invoice-c7-assignApprover:
                  value:
                  - management
  /usertask/example-invoice-c7/ApproveInvoiceUT:
    head:
      tags:
      - example-invoice-c7
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
            examples:
              ApproveInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out2'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/example-invoice-c7/PrepareBankTransferUT:
    head:
      tags:
      - example-invoice-c7
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
  /process/example-invoice-c7-review:
    head:
      tags:
      - example-invoice-c7-review
      summary: 'Process: example-invoice-c7-review'
      description: |+
        This starts the Review Invoice Process.


        <div class="diagramCanvas">
          <div class="diagram" id="example-invoice-c7-review-79605">
            <img onLoad="openFromUrl('example-invoice-c7-review.bpmn', new BpmnJS({ container: $('#example-invoice-c7-review-79605'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [example-invoice-c7-review.bpmn](diagrams/example-invoice-c7-review.bpmn)

      operationId: 'Process: example-invoice-c7-review'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              example-invoice-c7-review:
                value:
                  creditor: aaaaGreat Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out'
              examples:
                example-invoice-c7-review:
                  value:
                    clarified: true
  /usertask/example-invoice-c7-review/AssignReviewerUT:
    head:
      tags:
      - example-invoice-c7-review
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out3'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/example-invoice-c7-review/ReviewInvoiceUT:
    head:
      tags:
      - example-invoice-c7-review
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out4'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /usertask/UserTasks/ApproveInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
            examples:
              ApproveInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out2'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/UserTasks/PrepareBankTransferUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
  /usertask/UserTasks/AssignReviewerUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out3'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/UserTasks/ReviewInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out4'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /decisiondmn/DMNs/example-invoice-c7-assignApprover:
    head:
      tags:
      - DMNs
      summary: 'DecisionDmn: example-invoice-c7-assignApprover'
      description: |+
        Decision Table on who must approve the Invoice.


        <div class="diagramCanvas">
          <div class="diagram" id="example-invoice-c7-assignApprover-39250">
            <img onLoad="openFromUrl('example-invoice-c7-assignApprover.dmn', new DmnJS({ container: $('#example-invoice-c7-assignApprover-39250'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [example-invoice-c7-assignApprover.dmn](diagrams/example-invoice-c7-assignApprover.dmn)

      operationId: 'DecisionDmn: example-invoice-c7-assignApprover'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In1'
            examples:
              example-invoice-c7-assignApprover:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]'
              examples:
                example-invoice-c7-assignApprover:
                  value:
                  - management
                budget:
                  value:
                  - management
                day-to-day expense:
                  value:
                  - accounting
                  - sales
components:
  schemas:
    ApproverGroup:
      oneOf:
      - $ref: '#/components/schemas/accounting'
      - $ref: '#/components/schemas/management'
      - $ref: '#/components/schemas/sales'
    CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]:
      oneOf:
      - $ref: '#/components/schemas/ApproverGroup'
    In:
      required:
      - creditor
      - amount
      - invoiceCategory
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
        invoiceReviewedMock:
          $ref: '#/components/schemas/Out'
    In1:
      required:
      - amount
      - invoiceCategory
      type: object
      properties:
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
    In2:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
      description: Same Input as _InvoiceReceipt_, only without mocking - no mocking
        in UserTasks
    In3:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
        outputMock:
          $ref: '#/components/schemas/Out'
      description: Same Input as _InvoiceReceipt_, only different Mocking
    InvoiceCategory:
      oneOf:
      - $ref: '#/components/schemas/Misc'
      - $ref: '#/components/schemas/Software License Costs'
      - $ref: '#/components/schemas/Travel Expenses'
    Misc:
      type: object
    Out:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
      description: Mocking the subProcess _Invoice Receipt_.
    Out1:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer (only set if there was a review).
    Out2:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
      description: Every Invoice has to be accepted by the Boss.
    Out3:
      required:
      - reviewer
      type: object
      properties:
        reviewer:
          type: string
    Out4:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
    Software License Costs:
      type: object
    Travel Expenses:
      type: object
    accounting:
      type: object
    management:
      type: object
    sales:
      type: object
