name: CI
on:
  pull_request:
  push:
    branches: [ master, develop ]
jobs:
  testAndGenerateDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Coursier Cache
        uses: coursier/cache-action@v6  
      - name: Setup JDK
        uses: coursier/setup-action@v1
      - name: Compile
        run: sbt compile
      - name: Documentation
        run: sbt documentation/laikaSite
      - name: Test
        run: sbt -v "test:compile; domain/test; bpmn/test;"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report            # Name of the check run which will be created
          path: "**/test-reports/*.xml"    # Path to test results.
          reporter: java-junit        # Format of test results
