name: CI
on:
  pull_request:
  push:
    branches: [ master, develop ]
jobs:
  testAndGenerateDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Compile
        run: sbt compile
      - name: Documentation
        run: sbt laikaSite
      - name: Test
        run: sbt test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report            # Name of the check run which will be created
          path: "**/test-reports/*.xml"    # Path to test results.
          reporter: java-junit        # Format of test results
